---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: release
    repoURL: https://github.com/IanHewlett/demo-platform-service-external-secrets.git
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
