# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/IanHewlett/demo-platform-service-cert-manager.git
    path: overlays/local
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true

  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
