# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/IanHewlett/demo-platform-service-istio-system.git
    path: release/istio-base
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true

  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
