kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: "http://vault.vault.svc.cluster.local:8200"
  AVP_TYPE: "vault"
  AVP_AUTH_TYPE: "k8s"
  AVP_K8S_MOUNT_PATH: "local-minikube-us-east-0"
  AVP_K8S_ROLE: "di-admin-kubernetes-role"
