---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name # if it is possible to merge on file name, there is no need for a name field in instance values
        generators:
          - git:
              files:
                - path: cluster/${ROLE}/services/*.json
              repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
              requeueAfterSeconds: 20
              revision: "" # orchestration repo version for the role/env

          - git:
              files:
                - path: environments/${INSTANCE}/services/*.json
              repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
              requeueAfterSeconds: 20
              revision: "" # orchestration repo version for the role/env; all instances/cluster_names for a given role/env should share the same orchestration repo version

  syncPolicy:
    preserveResourcesOnDeletion: false

  template:
    metadata:
      name: '{{.name}}-release'
      namespace: argocd

    spec:
      project: default

      source:
        repoURL: '{{.source_url}}'
        path: '{{.source_path}}'
        targetRevision: '{{.source_version}}'
#        plugin:
#          name: argocd-vault-plugin  # Enable AVP

      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.namespace}}'

      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true

  templatePatch: |
    {{- if .create_namespace }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        {{- if .namespace_labels }}
        managedNamespaceMetadata:
          labels:
            {{- range $labelKeyPair := .namespace_labels }}
            {{ $labelKeyPair }}
            {{- end }}
        {{- end }}
    {{- end }}

    {{- if .helm_values }}
    spec:
      source:
        kustomize:
          patches:
            - target:
                kind: Application
                name: {{ .name }}
              patch: |
                - op: add
                  path: /spec/sources/0/helm/parameters
                  value:
                  {{- range $param:= .helm_values }}
                    - name: {{ $param.key }}
                      value: '{{ $param.value }}'
                  {{- end }}
    {{- end }}

    {{- if .kustomization_values }}
    spec:
      source:
        kustomize:
          patches:
          {{- range $kustomization:= .kustomization_values }}
            - target:
                kind: {{ $kustomization.kind }}
                name: {{ $kustomization.name }}
              patch: |
                - op: add
                  path: {{ $kustomization.path }}
                  value: {{ $kustomization.value }}
          {{- end }}
    {{- end }}
