---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  generators:
    - git:
        files:
          - path: cluster/services/*.json
        repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
        requeueAfterSeconds: 20
        revision: ""
        template:
          metadata: {}
          spec:
            destination: {}
            project: ""

  syncPolicy:
    preserveResourcesOnDeletion: false

  template:
    metadata:
      name: '{{name}}-release'
      namespace: argocd

    spec:
      project: default

      source:
        repoURL: '{{source_url}}'
        path: '{{source_path}}'
        targetRevision: '{{source_version}}'

      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true

  templatePatch: |
    {{- if .create_namespace }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
    {{- end }}
