apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: serviceset
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: cluster/services/*.json
      repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{name}}-release'
      namespace: argocd
    spec:
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/IanHewlett/demo-platform-service-{{name}}.git'
        targetRevision: '{{version}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: argocd
      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true
