---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: cluster/services
    repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
    targetRevision: 0.0.5
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
