---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - git:
              files:
                - path: environments/local/services/*.json
              repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
              requeueAfterSeconds: 20
              revision: ""
#              template:
#                metadata: {}
#                spec:
#                  destination: {}
#                  project: ""
          - git:
              files:
                - path: environments/local-minikube-us-east-0/services/*.json
              repoURL: https://github.com/IanHewlett/demo-platform-extension-argocd.git
              requeueAfterSeconds: 20
              revision: ""
#              template:
#                metadata: {}
#                spec:
#                  destination: {}
#                  project: ""

  syncPolicy:
    preserveResourcesOnDeletion: false

  template:
    metadata:
      name: '{{.name}}-release'
      namespace: argocd

    spec:
      project: default

      source:
        repoURL: '{{.source_url}}'
        path: '{{.source_path}}'
        targetRevision: '{{.source_version}}'

      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{.namespace}}'

      syncPolicy:
        automated:
          allowEmpty: true
          selfHeal: true

  templatePatch: |
    {{- if .create_namespace }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        {{- if .label_namespace }}
        managedNamespaceMetadata:
          labels:
            {{- range $labelKeyPair := .namespace_labels }}
            {{ $labelKeyPair }}
            {{- end }}
        {{- end }}
    {{- end }}
