apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connaisseur-release
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd-autopilot
    app.kubernetes.io/name: connaisseur-release
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IanHewlett/demo-platform-service-connaisseur.git
    path: release
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
