---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connaisseur-release
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: release
    repoURL: https://github.com/IanHewlett/demo-platform-service-connaisseur.git
    targetRevision: 0.0.2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
