---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: ApplicationSet
      name: services
    patch: |
      - op: add
        path: /spec/generators/0/merge/generators/0/git/files/0/path
        value:
          environments/local/services/*.json
