---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd

spec:
  project: default

  source:
    path: secrets
    repoURL: https://github.com/IanHewlett/demo-platform-service-external-secrets.git

#    plugin:
#      name: argocd-vault-plugin-kustomize

#    kustomize:
#      patches:
#        - target:
#            kind: ClusterSecretStore
#            name: vault-admin
#          patch: |
#            - op: add
#              path: /spec/provider/vault/auth/kubernetes/mountPath
#              value: local-minikube-us-east-0

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated: {}
