---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd

spec:
  project: default

  source:
    path: secrets
    repoURL: https://github.com/IanHewlett/demo-platform-service-external-secrets.git

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated: {}
