# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-cluster-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/IanHewlett/demo-platform-service-external-secrets.git
    path: secrets
    targetRevision: 0.0.5
    kustomize:
      patches:
        - target:
            kind: Application
            name: cluster
          patch: |
            - op: add
              path: /spec/provider/vault/server
              value:
                http://vault.vault.svc.cluster.local:8200
            - op: add
              path: /spec/provider/vault/auth/kubernetes/mountPath
              value:
                local-minikube-us-east-0

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true

  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
