name: Minikube
on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - uses: extractions/setup-just@v1
        with:
          just-version: 1.25.2

      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        # now you can run kubectl to see the pods in the cluster

      - name: label nodes
        run: |
          kubectl label nodes minikube "nodegroup"="management-nodes"
          kubectl label nodes minikube "node.kubernetes.io/role"="management"

      - name: install vault
        run: just vault github-minikube-us-east-0

      - name: bootstrap argocd
        run: ./scripts/bootstrap.sh github github-minikube-us-east-0

#      - name: run spec test for the argocd core installation
#        run: ./scripts/test.sh

      - name: wait for argocd core installation to be ready
        run: ./scripts/ready.sh

      - name: Try the cluster!
        run: kubectl get pods -A
